### ISSUE TITLE
Stylemix & morphing

### ISSUE THREAD

**Issue by shahik** [Seanseattle/SMIS#8]
Hi, 
     Thank you for such an Awesome paper. How can I perform Stylemix on a single instance from Latent codes, 2nd by feeding real_images into latent code and then perform stylemix so any script for this? 
How can I perform style_morphing on Real & generated deep_fashion designs? Any script ? thanks!

**Comment by Seanseattle** [comment]
Hello, for style morphing, you can sample two latent codes and make an interpolation between two latent codes. For style mix, just combine the style codes to get latent code, like [SMIS test](https://github.com/Seanseattle/SMIS/blob/5d2b74794059ad1ddeb4573e2b1bf2d1fa29adb2/models/smis_model.py#L257.).

**Comment by shahik** [comment]
thanks for reaching out. I am getting encodings by the following code in test file & have NoneType object error?

        
     from numpy import save
     for i, data_i in tqdm(enumerate(dataloader)):  
     mu, logvar = model(data_i, mode='encode_only')
     # save to npy file
     save('mu.npy', mu)
     save('logvar.npy', logvar)

error: 
      
Traceback (most recent call last):
  File "/content/SMIS/test.py", line 32, in <module>
    mu, logvar = model(data_i, mode='encode_only')
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/SMIS/models/smis_model.py", line 51, in forward
    z, mu, logvar = self.encode_z(real_image)
  File "/content/SMIS/models/smis_model.py", line 191, in encode_z
    mu, logvar = self.netE(real_image)
**TypeError:** 'NoneType' object is not callable

**Comment by shahik** [comment]
Each time it delivers different results without changing any parameters in Vis_test. How can I control stylemixing of Upper_clothes/Pants/Hair just one at a time like only upper_clothes with specific colors chosen by me? Which parameters will do that? thanks!

**Comment by Seanseattle** [comment]
Hi! The codes do not create the Encoder model at test mode as most pictures are generated from noise. https://github.com/Seanseattle/SMIS/blob/5d2b74794059ad1ddeb4573e2b1bf2d1fa29adb2/models/smis_model.py#L99 And we don't upload the Encoder pretrained model to the Google Drive. There is no direct function for stylemixing, however, it is easy to write code for this. Firstly, create or load some latent codes(noise), then, combine different latent code for stylemixing. Each channel represents a semantic class.

**Comment by shahik** [comment]
Plz release atleast a Sample Notebook  🙏🙏🙏
